name: Continuous integration

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          
      - run: yarn install
      - run: yarn test

      - name: E2E simple test case
        uses: ./
        with:
          version: 1.0.0
          manifest: __tests__/fixtures/simple/Cargo.toml

      - name: Assert
        run: |
          cd __tests__/fixtures/simple
          git diff --no-index --exit-code ./Cargo.toml ./Cargo.expected.toml

      - name: E2E real_world_cnd test case
        uses: ./
        with:
          version: 0.6.0
          manifest: __tests__/fixtures/real_world_cnd/Cargo.toml

      - name: Assert
        run: |
          cd __tests__/fixtures/real_world_cnd
          git diff --no-index --exit-code ./Cargo.toml ./Cargo.expected.toml
